---
version: '3'
services:
        mysql:
                image: mysql:5.7
                command: --init-file /home/ubuntu/inittables.sql
                volumes:
                        -  /home/ubuntu/inittables.sql:/data/application/inittables.sql
                environment:
                 MYSQL_ROOT_PASSWORD: password
        devfrontend:
                image: balajimanipi/frontenddev:29
                ports:
                 - "8080:8080"
                links:
                 - devauthservice:devfrontend
        devauthservice:
                image: balajimanipi/authservice:29
                ports:
                 - "8081:8081"
                links:
                 - mysql:devauthservice
                 - mysql:devfrontend
...
